version: "3.8"
services:
   silverstripe:
      image: brettt89/silverstripe-web:8.1-apache
      build: .
      volumes:
         - .:/var/www/html
      ports:
         - 80:80
      depends_on:
         - database
      environment:
         - DOCUMENT_ROOT=/var/www/html
         - SS_TRUSTED_PROXY_IPS=*

   database:
      image: mysql:5.7
      environment:
         - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      volumes:
         - db-data:/var/lib/mysql

   phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
         - 8080:80
      depends_on:
         - database
      environment:
         - PMA_HOST=database
         - UPLOAD_LIMIT=1G

   mailhog:
      image: mailhog/mailhog:v1.0.0
      ports:
         - 1025:1025
         - 8025:8025
volumes:
   db-data: